Allow cleanup of buckets even if there are objects in them
terraform-google-modules/terraform-google-gke-gitlab pull request #72
Opened 2021-02-22 01:19 UTC by a200462790

Addresses #49 

I named the variable a bit generic because when we upgrade the google provider, deleting the google_sql_database_instance will require an additional [flag](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#deletion_protection), and I figured we could reuse this variable.

2021-03-22 15:35 UTC, morgante requested changes

2021-03-22 15:35 UTC, morgante commented on variables.tf
> +variable "allow_future_deletion" {
```suggestion
variable "allow_force_destroy" {
```

2021-04-05 17:53 UTC, a200462790 commented on variables.tf
> +variable "allow_future_deletion" {
Done!

2021-04-05 18:20 UTC, morgante approved these changes

2021-04-05 18:21 UTC, merged